### PR TITLE
Add support for variable $TDCREATE.

### PR DESCRIPTION
**Pull request by dismine**
According to documentation $TDCREATE has code 40 and contains "Local date/time of drawing creation (see “Special Handling of Date/Time Variables”)".

### CODE REVIEW

**Comment by whitequark** [comment]
Because I've combined your commits "Added more codes for colors supported by DXF." and "Sort colors codes by their numeric value." while merging, this pull request now has four commits instead of one. Do you think you can rebase it? `git fetch upstream && git rebase upstream/master` is how I usually do it.

**Comment by dismine** [comment]
Can you help me with Git? What steps should i do to continue successfully send patches? My skills in git are pretty basic.

**Comment by dismine** [comment]
@whitequark maybe you prefer to get all changes in one pull request? :)

**Comment by whitequark** [comment]
> What steps should i do to continue successfully send patches?

If you do `git pull --rebase upstream master` after I successfully merge a pull request you should be all fine!

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
