### PR TITLE
Fix writing a polyline. Missed braces.

### PR DESCRIPTION
**Pull request by dismine**
If judge by indentation this is a bug.

### CODE REVIEW

**Comment by whitequark** [comment]
@Evil-Spirit can you confirm that was a bug? it was your commit altering the condition

**Comment by dismine** [comment]
I cannot because of AutoCAD. I just tested both cases and both are valid. But.

Variable **is3d** used only if _version > DRW::AC1009_.  Feel free to reject.

**Comment by dismine** [comment]
Hey guys, any progress on this? I still have several patches for you.

**Comment by whitequark** [comment]
@dismine You can submit every patch (that doesn't depend on each other) as a separate pull request, I'll merge them quickly.

**Comment by dismine** [comment]
Sounds good, but when i tried all next commits go to last opened pull request. Remember my first pull request?

**Comment by whitequark** [comment]
You can do it like this:
```
git checkout master
git pull upstream master
git checkout -b feature-x master
git commit -m "Add feature x"
git push origin feature-x
```
and then create a pull request from that branch, GitHub will prompt you if you open this repo (or your fork, I don't recall exactly).

**Comment by dismine** [comment]
Thanks, i will try right now.

**Comment by whitequark** [comment]
@dismine I think you've clobbered the commit that was in this branch before, can you put it back?

**Comment by dismine** [comment]
Actually i tested changes with AutoCAD and it doesn't see any difference. So, let's left all as it is now.

**Comment by whitequark** [comment]
OK, thanks.

**Pull request closed without merging**
